#!/usr/bin/env bash
# Generate .env at the repo root from the current az session and the
# live Pulumi stack outputs. Re-run after any `pulumi up` that changes
# outputs.
set -euo pipefail

cd "$(dirname "$0")/.."   # repo root
INFRA="./infra"

require() {
  command -v "$1" >/dev/null 2>&1 || { echo "missing: $1" >&2; exit 1; }
}
require az
require pulumi

# This stack uses the passphrase secrets provider, so reading outputs
# needs the passphrase even though our outputs are not secrets.
if [ -z "${PULUMI_CONFIG_PASSPHRASE+x}" ] && [ -z "${PULUMI_CONFIG_PASSPHRASE_FILE+x}" ]; then
  cat >&2 <<MSG
PULUMI_CONFIG_PASSPHRASE is not set.

Export it before running this script (use an empty value if you didn't
set a passphrase at \`pulumi stack init\`):

  export PULUMI_CONFIG_PASSPHRASE=""        # if no passphrase
  export PULUMI_CONFIG_PASSPHRASE=<yours>   # if you set one

Or set PULUMI_CONFIG_PASSPHRASE_FILE to a file containing it.
MSG
  exit 1
fi

SUBSCRIPTION_ID=$(az account show --query id -o tsv)
RG=$(pulumi -C "$INFRA" stack output resourceGroupName)
LOC=$(pulumi -C "$INFRA" config get azure-native:location)
SA=$(pulumi -C "$INFRA" stack output storageAccountName)
CONTAINER=$(pulumi -C "$INFRA" stack output containerName)
NS_FQDN=$(pulumi -C "$INFRA" stack output eventHubNamespaceFqdn)
HUB=$(pulumi -C "$INFRA" stack output eventHubName)

cat > .env <<EOF
# Generated by scripts/dump-env.sh — re-run after any pulumi up that
# changes outputs. Gitignored.

AZURE_SUBSCRIPTION_ID=${SUBSCRIPTION_ID}
KEEP_RESOURCE=1

AZURE_RESOURCE_GROUP=${RG}
AZURE_LOCATION=${LOC}
STORAGE_ACCOUNT_NAME=${SA}
BLOB_CONTAINER_NAME=${CONTAINER}
EVENT_HUB_NAMESPACE_FQDN=${NS_FQDN}
EVENT_HUB_NAME=${HUB}
EOF

echo "wrote .env"
